### ISSUE TITLE
Crud pizzas

### ISSUE THREAD

**Issue by kjkGustavo** [PoorlyDefinedBehaviour/Appizza#6]
- Como administrador do app quero ser capaz de:
  - Listar uma ou todas as pizzas que estão disponíveis
  - Adicionar mais uma pizza
  - Atualizar as informações de uma pizza 
  - Deletar uma ou mais pizzas 
  
- Como usuário do app quero ser capaz de:
  - Listar todas as pizzas que estão disponíveis

**Comment by PoorlyDefinedBehaviour** [comment]
Essa task esta detalhada na issue #27
