### ISSUE TITLE
Crud cupons de desconto

### ISSUE THREAD

**Issue by kjkGustavo** [PoorlyDefinedBehaviour/Appizza#7]
- Como administrador do app quero ser capaz de:
  - Criar um novo cupom de desconto com código customizado(exemplo: HELLOWORLD123)
  - Deletar um cupom de desconto
  - Atualizar um cupom de desconto
  - Listar um ou mais cupons de desconto

- Como usuário do app quero ser capaz de:
  - Utilizar um cupom de desconto

**Comment by PoorlyDefinedBehaviour** [comment]
Com mais detalhes na #25
